CREATE TABLE USER_PROFILE (
	USER_ID NUMBER(19) NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	MIDDLE_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(50)
);

CREATE SEQUENCE USER_PROFILE_SEQ MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20;